driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: append
    run_list: test::append
  - name: append_existing
    run_list: test::append_existing
  - name: create
    run_list: test::create
  - name: create_if_missing
    run_list: test::create_if_missing
  - name: default
    run_list: test::default
  - name: options
    run_list: test::options
  - name: unique
    run_list: test::unique
